# Generated by Django 6.1 on 2026-09-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0002_alumno_usuario'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('alumno', 'dictado_materia'), name='inscripcion_unica_alumno_dictado'),
        ),
    ]
