# Generated by Django 6.1 on 2026-09-21 14:38

import UTN.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0002_alumno_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='codigo_inscripcion',
            field=models.CharField(default=UTN.models._generar_codigo, editable=False, max_length=30, unique=True),
        ),
    ]
